name: Node Pipeline
on: push
jobs:
  main:
    strategy:
      matrix: 
        node: ['18.x', '19.x']
    uses: n00bc0der89/actions-learning-pathway/.github/workflows/build-test-deploy.yml@feature/new-feature
    with:
      node-version: ${{ matrix.node }}
